package com.aimall.server.service.impl;
import com.aimall.server.entity.*; import com.aimall.server.mapper.*; import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import org.springframework.scheduling.annotation.Scheduled; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDateTime; import java.util.List;
@Service public class ReturnWorkflowService {
 private final OmsOrderReturnApplyMapper applies; private final OmsReturnEvidenceMapper evidence; private final OmsReturnStatusEventMapper events; private final OmsOrderReturnItemMapper returnItems; private final OmsOrderItemMapper orderItems;
 public ReturnWorkflowService(OmsOrderReturnApplyMapper a,OmsReturnEvidenceMapper e,OmsReturnStatusEventMapper s,OmsOrderReturnItemMapper r,OmsOrderItemMapper o){applies=a;evidence=e;events=s;returnItems=r;orderItems=o;}
 @Transactional public OmsReturnEvidence addEvidence(Long memberId,Long applyId,String mediaType,String url){var a=applies.selectById(applyId);if(a==null||!memberId.equals(a.getMemberId()))throw new RuntimeException("售后申请不存在");if(a.getStatus()==null||a.getStatus()!=0)throw new RuntimeException("仅待审核申请可补充凭证");String type=mediaType.trim().toUpperCase();if(!type.equals("IMAGE")&&!type.equals("VIDEO"))throw new IllegalArgumentException("凭证类型只支持 IMAGE 或 VIDEO");if(url==null||url.isBlank()||url.length()>1000)throw new IllegalArgumentException("凭证地址不正确");if(evidence.selectCount(new LambdaQueryWrapper<OmsReturnEvidence>().eq(OmsReturnEvidence::getReturnApplyId,applyId))>=12)throw new RuntimeException("单个售后最多上传 12 个凭证");OmsReturnEvidence e=new OmsReturnEvidence();e.setReturnApplyId(applyId);e.setMemberId(memberId);e.setMediaType(type);e.setMediaUrl(url.trim());e.setCreateTime(LocalDateTime.now());evidence.insert(e);return e;}
 public List<OmsReturnEvidence> evidence(Long id){return evidence.selectList(new LambdaQueryWrapper<OmsReturnEvidence>().eq(OmsReturnEvidence::getReturnApplyId,id).orderByAsc(OmsReturnEvidence::getId));}
 @Transactional public OmsOrderReturnApply submitLogistics(Long memberId,Long id,String carrier,String tracking){if(carrier==null||carrier.isBlank()||tracking==null||tracking.isBlank())throw new IllegalArgumentException("退货承运商和物流单号不能为空");if(applies.submitReturnLogistics(id,memberId,carrier.trim(),tracking.trim())!=1)throw new RuntimeException("当前售后不可提交退货物流");record(id,1,7,"RETURN_SHIPPED",memberId,"MEMBER",carrier+":"+tracking);return applies.selectById(id);}
 @Transactional public OmsOrderReturnApply inspect(Long adminId,Long id,boolean accepted,String note){if(note==null||note.isBlank())throw new IllegalArgumentException("验货说明不能为空");String result=accepted?"ACCEPTED":"REJECTED";int target=accepted?8:9;if(applies.inspectReceived(id,target,result,note.trim())!=1)throw new RuntimeException("当前售后不可验货");if(!accepted){for(var item:returnItems.selectList(new LambdaQueryWrapper<OmsOrderReturnItem>().eq(OmsOrderReturnItem::getReturnApplyId,id))){if(orderItems.releaseReturnQuantity(item.getOrderItemId(),item.getQuantity())!=1)throw new RuntimeException("验货拒绝后释放退货数量失败");}}record(id,7,target,"INSPECTED",adminId,"ADMIN",result+":"+note);return applies.selectById(id);}
 public List<OmsReturnStatusEvent> events(Long id){return events.selectList(new LambdaQueryWrapper<OmsReturnStatusEvent>().eq(OmsReturnStatusEvent::getReturnApplyId,id).orderByAsc(OmsReturnStatusEvent::getId));}
 public void record(Long id,Integer from,Integer to,String type,Long op,String opType,String note){OmsReturnStatusEvent e=new OmsReturnStatusEvent();e.setReturnApplyId(id);e.setFromStatus(from);e.setToStatus(to);e.setEventType(type);e.setOperatorId(op);e.setOperatorType(opType);e.setNote(note);e.setCreateTime(LocalDateTime.now());events.insert(e);}
 @Scheduled(fixedDelayString="${aimall.return.sla-scan-delay-ms:60000}") public void markOverdue(){applies.markSlaOverdue();}
}
