param([string]$Root=(Split-Path -Parent $PSScriptRoot),[string]$Output=".acceptance/stage15/outbox-gate.json",[switch]$RequireProduction)
$ErrorActionPreference="Stop";$root=[IO.Path]::GetFullPath($Root);$checks=[Collections.Generic.List[object]]::new()
function Read-Utf8([string]$p){[IO.File]::ReadAllText((Join-Path $root $p),[Text.UTF8Encoding]::new($false,$true))}
function Read-Json([string]$p) { Get-Content (Join-Path $root $p) -Raw -Encoding UTF8 | ConvertFrom-Json }
function Add-Check($id,$name,[bool]$engineering,[bool]$production,$evidence){$checks.Add([ordered]@{id=$id;name=$name;engineeringReady=$engineering;productionReady=$production;evidence=$evidence})}
$entity=Read-Utf8 "aimall-server/src/main/java/com/aimall/server/entity/OutboxEvent.java";$mapper=Read-Utf8 "aimall-server/src/main/java/com/aimall/server/mapper/OutboxEventMapper.java";$service=Read-Utf8 "aimall-server/src/main/java/com/aimall/server/service/impl/OutboxEventService.java";$worker=Read-Utf8 "aimall-server/src/main/java/com/aimall/server/service/impl/OutboxWorker.java";$types=Read-Utf8 "aimall-server/src/main/java/com/aimall/server/outbox/OutboxEventType.java";$migration=Read-Utf8 "aimall-server/src/main/resources/db/migration/V20260720_1500__outbox_event_contract.sql"
$order=Read-Utf8 "aimall-server/src/main/java/com/aimall/server/service/impl/OrderServiceImpl.java";$inventory=Read-Utf8 "aimall-server/src/main/java/com/aimall/server/service/impl/InventoryServiceImpl.java";$payment=Read-Utf8 "aimall-server/src/main/java/com/aimall/server/service/impl/PayServiceImpl.java";$query=Read-Utf8 "aimall-server/src/main/java/com/aimall/server/service/impl/PaymentQueryStateService.java";$returns=Read-Utf8 "aimall-server/src/main/java/com/aimall/server/service/impl/ReturnApplyServiceImpl.java";$refund=Read-Utf8 "aimall-server/src/main/java/com/aimall/server/service/impl/RefundTaskStateService.java";$knowledge=Read-Utf8 "aimall-server/src/main/java/com/aimall/server/service/impl/KnowledgePublicationServiceImpl.java";$tests=Read-Utf8 "aimall-server/src/test/java/com/aimall/server/service/impl/OutboxWorkerTest.java";$mysql=Read-Json ".acceptance/stage15/mysql.json";$java=Read-Json ".acceptance/stage15/java-tests.json"
$fixed=@("OrderCreated","InventoryReserved","InventoryReleased","PaymentCreated","PaymentSucceeded","PaymentFailed","PaymentUnknown","RefundRequested","RefundSucceeded","KnowledgePublished","KnowledgeDeleted")
$registered = @($fixed | Where-Object { -not $types.Contains('"' + $_ + '"') }).Count -eq 0
$producers = $order.Contains("ORDER_CREATED") -and $inventory.Contains("INVENTORY_RESERVED") -and
    $inventory.Contains("INVENTORY_RELEASED") -and $payment.Contains("PAYMENT_CREATED") -and
    $payment.Contains("PAYMENT_SUCCEEDED") -and $query.Contains("PAYMENT_FAILED") -and
    $query.Contains("PAYMENT_UNKNOWN") -and $returns.Contains("REFUND_REQUESTED") -and
    $refund.Contains("REFUND_SUCCEEDED") -and $knowledge.Contains("KNOWLEDGE_PUBLISHED") -and
    $knowledge.Contains("KNOWLEDGE_DELETED")
Add-Check "S15-01" "Unified versioned Outbox schema" ($entity.Contains("occurredAtUtc") -and $entity.Contains("producerVersion") -and $entity.Contains("payloadSchemaVersion") -and $migration.Contains("occurred_at_utc") -and $migration.Contains("producer_version") -and $migration.Contains("payload_schema_version")) $false "isolated MySQL passed; production migration pending"
Add-Check "S15-02" "Canonical event envelope" ($service.Contains('envelope.put("eventId"') -and $service.Contains('envelope.put("occurredAtUtc"') -and $service.Contains('envelope.put("producerVersion"') -and $service.Contains('envelope.put("payloadSchemaVersion"')) $true "versioned envelope with UTC occurrence"
Add-Check "S15-03" "Atomic claim, lease, retry and dead letter" ($mapper.Contains("status IN ('NEW', 'RETRY')") -and $mapper.Contains("lease_until < NOW(6)") -and $mapper.Contains("status = 'DEAD_LETTER'") -and $worker.Contains("delaySeconds")) $false "real MySQL contention passed; production multi-instance soak pending"
Add-Check "S15-04" "Fixed event registry" $registered $true "all 11 event names exact"
Add-Check "S15-05" "Transactional business producers" $producers $true "order, inventory, payment, refund and knowledge producers"
Add-Check "S15-06" "Durable refund consumer" ($worker.Contains('case "RefundRequested"') -and $worker.Contains("refundTaskProcessor.process") -and $tests.Contains("refundRequestedIsConsumedByDurableWorkerAndMarkedSent")) $true "Outbox drives refund state machine with CAS/recovery"
Add-Check "S15-07" "External calls outside local transaction" ($knowledge.Contains("transactionTemplate.execute") -and $knowledge.Contains("applyMilvusActivation(plan)") -and $worker.Contains("paymentQueryService.processById") -and $worker.Contains("latePaymentProcessor.process")) $true "unknown outcomes use query/recovery"
Add-Check "S15-08" "Regression and operations evidence" ([bool]$java.passed -and [bool]$mysql.passed -and [int]$mysql.tests -eq 22) $false "production dead-letter alert delivery and acknowledgement pending"
$ef=@($checks | Where-Object { -not $_.engineeringReady });$pf=@($checks | Where-Object { -not $_.productionReady });$result=[ordered]@{stage=15;source="AIMALL_ENGINEERING_PRODUCTION_REMEDIATION_PLAN.md section 15";generatedAt=[DateTimeOffset]::Now.ToString("o");total=$checks.Count;engineeringPassedCount=$checks.Count-$ef.Count;engineeringPassed=$ef.Count -eq 0;productionPassedCount=$checks.Count-$pf.Count;productionPassed=$pf.Count -eq 0;checks=$checks;productionBlockers=@("production database migration and validation","multi-instance production lease takeover soak","dead-letter production alert delivery and acknowledgement")}
$out=[IO.Path]::GetFullPath((Join-Path $root $Output));[IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($out))|Out-Null;[IO.File]::WriteAllText($out,($result | ConvertTo-Json -Depth 8),[Text.UTF8Encoding]::new($false));if(-not $result.engineeringPassed){throw "Stage 15 engineering gate failed: $($ef.id -join ',')"};if($RequireProduction -and -not $result.productionPassed){throw "Stage 15 production gate failed: $($pf.id -join ',')"};$result | ConvertTo-Json -Depth 8
